Proyecto/Controllers/CalificacionesController.cs
using ContratosControladorApp1.Contratos;
using ContratosControladorApp1.DTO;
using Proyecto.Mapeadores;
using Proyecto.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Proyecto.Controllers
{
    public class CalificacionesController:Controller
    {
        ICalificacionApp _controlador;
        public CalificacionesController(ICalificacionApp app)
        {
            _controlador = app;

        }

        public ActionResult Index(String nombre)
        {
            MapeadorUICalificaciones mapeador = new MapeadorUICalificaciones();
            IEnumerable<CalificacionesDTO> ListaCalificacionDTO = _controlador.ConsultaCalificaciones();
            IEnumerable<CalificacionesModel> model = mapeador.MapearT1T2(ListaCalificacionDTO);
            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Create(CalificacionesModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    MapeadorUICalificaciones mapeador = new MapeadorUICalificaciones();
                    CalificacionesDTO dto = mapeador.MapearT2T1(model);
                    bool guardado = _controlador.RegistrarCalificacion(dto);
                    if (guardado)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        return View(model);
                    }
                }
                else
                {
                    return View(model);
                }
            }
            catch
            {
                return View();
            }
        }
    }
}

Proyecto/Controllers/ReservaController.cs
using ContratosControladorApp1.Contratos;
using ContratosControladorApp1.DTO;
using Proyecto.Mapeadores;
using Proyecto.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Diagnostics;

namespace Proyecto.Controllers
{
    public class ReservaController : Controller
    {
        IReservaApp _controlador;
        public ReservaController(IReservaApp app)
        {
            _controlador = app;

        }

        public ActionResult Index()
        {
            MapeadorUIReserva mapeadorReserv = new MapeadorUIReserva();
            IEnumerable<ReservaDTO> ListaReservaDTO = _controlador.ConsultaReserva();
            IEnumerable<ReservaModel> model = mapeadorReserv.MapearT1T2(ListaReservaDTO);
            return View(model);
        }

        [HttpPost]
        public ActionResult Buscar(DateTime fecha, TimeSpan hora)
        {

            Boolean Validacion = _controlador.BuscarReserva(fecha, hora);
            if (Validacion)
            {

                Create(
                   new ReservaModel()
                   {
                       Id_cliente = 1,
                       Id_reservacion = 2,
                       fecha = fecha,
                       hora = hora,
                       Total = 40000,
                       Estadoreserva = "h",
                       Tipopago = "Tarjeta",
                       Factura = "1"
                   }
                    );

                Response.Write("<script languaje=javascript>alert('¡La reserva ha sido registrada exitosamente');</script>");
                return Redirect("../Servicio/Index");
            }
            else
            {
                Response.Write("<script languaje=javascript>alert('¡La reserva a la hora indicada no se encuentra disponible! Porfavor selecciones otra hora');</script>");
                return View("Index");
            }
        }
        public ActionResult Buscar()
        {
            return View();
        }
        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Create(ReservaModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    MapeadorUIReserva mapeador = new MapeadorUIReserva();
                    ReservaDTO dto = mapeador.MapearT2T1(model);
                    bool guardado = _controlador.RegistrarReserva(dto);
                    if (guardado)
                    {
                        return RedirectToAction("../Home/Index");
                    }
                    else
                    {
                        return View(model);
                    }
                }
                else
                {
                    return View(model);
                }
            }
            catch
            {
                return View();
            }
        }
    }
}

Proyecto/Controllers/ServicioController.cs
using ContratosControladorApp1.Contratos;
using ContratosControladorApp1.DTO;
using Proyecto.Mapeadores;
using Proyecto.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Proyecto.Controllers
{
    public class ServicioController:Controller
    {
        IServicioApp _controlador;
        public ServicioController(IServicioApp app)
        {
            _controlador = app;

        }
        public ActionResult Index()
        {
            MapeadorUIServicio mapeador = new MapeadorUIServicio();
            IEnumerable<ServicioDTO> ListaServicioDTO = _controlador.ConsultaServicios();
            IEnumerable<ServicioModel> model = mapeador.MapearT1T2(ListaServicioDTO);
            return View(model);
        }
        public ActionResult Detalle(int id)
        {
            MapeadorUIServicio mapeador = new MapeadorUIServicio();
            ServicioDTO dto = _controlador.BuscarServicio(id);
            ServicioModel modelo = mapeador.MapearT1T2(dto);
            return View(modelo);
        }
        public ActionResult Calificar()
        {
            return View();
        }
        public ActionResult Create()
        {
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Create(ServicioModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    MapeadorUIServicio mapeador = new MapeadorUIServicio();
                    ServicioDTO dto = mapeador.MapearT2T1(model);
                    bool guardado = _controlador.RegistrarServicio(dto);
                    if (guardado)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        return View(model);
                    }
                }
                else
                {
                    return View(model);
                }
            }
            catch
            {
                return View();
            }
        }
    }
}

Proyecto/Controllers/UsuarioController.cs
using ContratosControladorApp1.Contratos;
using ContratosControladorApp1.DTO;
using Proyecto.Mapeadores;
using Proyecto.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Proyecto.Controllers
{
    public class UsuarioController : Controller
    {
        IUsuarioApp _controlador;
        public UsuarioController(IUsuarioApp app)
        {
            _controlador = app;

        }

        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Create(UsuarioModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (model.Contraseña2.Equals(model.Contraseña))
                    {
                        UsuarioModel model2 = new UsuarioModel()
                        {
                            Id_usuario = model.Id_usuario,
                            Nombre = model.Nombre,
                            Contraseña = model.Contraseña
                        };
                        MapeadorUIUsuario mapeador = new MapeadorUIUsuario();
                        UsuarioDTO dto = mapeador.MapearT2T1(model2);
                        bool guardado = _controlador.IngresarUsuario(dto);
                        if (guardado)
                        {
                            return RedirectToAction("../Home/Index");
                        }
                        else
                        {
                            return View(model);
                        }
                    }
                    else
                    {
                        return View(model);
                    }
                }
                else
                {
                    return View(model);
                }
            }
            catch
            {
                return View();
            }
        }



        public ActionResult Ingresar()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Ingresar(UsuarioModel user)
        {

            if (IsValid(user.Nombre, user.Contraseña).Equals(""))
            {
                ModelState.AddModelError("", "Inicio de sesión incorrecta.");
                Debug.WriteLine("Inicio de sesión incorrecta");

            }
            else
            {
                FormsAuthentication.SetAuthCookie(user.Nombre, false);
                Debug.WriteLine("Inicio de sesión");
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        public ActionResult Salir()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }



        private string IsValid(string nombre, string pass)
        {
            string isValid = _controlador.IsValid(nombre, pass);
            return isValid;
        }

    }
}

Proyecto/Views/Servicio/Create.cshtml
@model Proyecto.Models.ServicioModel
@{
    ViewBag.Title = "Create";
}


<h2>Create</h2>

<table class="table">
    <tr>
        <th>
            Nombre
        </th>
        <th>
            Descripción
        </th>
        <th>
            Imagen
        </th>
    </tr>


    <tr>
        <td>
            @Html.DisplayFor(model => model.Nombre_servicio)
        </td>
        <td>
            @Html.DisplayFor(model => model.descripcion_servicio)
        </td>
        <td>
            @Html.DisplayFor(model => model.Imagen)
        </td>
    </tr>
</table>

Proyecto/Views/Servicio/Detalle.cshtml
@model Proyecto.Models.ServicioModel
@{
    ViewBag.Title = "Detalle";
}


<div>
    <div class="btn-volver">@Html.ActionLink("<< Volver atras", "Index", "Servicio", new { @class = "btnvolver" })</div>
    <div>
        <h2 class="title-detail"> @Html.DisplayFor(model => model.Nombre_servicio)</h2>
    </div>
    <div class="cont-img-detail">
        <img src="~/Imagenes/servicios/@Html.DisplayFor(model => model.Imagen)" alt=""/>
    </div>
    <div class="body-detail">
        <p>@Html.DisplayFor(model => model.descripcion_servicio)</p>
    </div>
    <div class="price">
        <p>Precio: $@Html.DisplayFor(model => model.Precio)</p>
    </div>

    <div class="cont-btns" align="center">
        @if (User.Identity.IsAuthenticated)
        {
            <a href="@Url.Action("Index", "Reserva")" class="boton btnreservar">Reservar servicio</a>
        <a href="@Url.Action("Index", "Calificaciones", new { id = Model.Servicio })" class="boton btncalificar">Calificar servicio</a>
        }
        else
        {
            <h4 class="texto-inicio-sesion">Debes iniciar sesión para poder contratar y calificar nuestros servicios</h4>
            <a href="@Url.Action("Ingresar", "Usuario")" class="boton btncalificar">Ir a inicio de sesión</a>
        }
    </div>
</div>

@Styles.Render("~/Content/stylesdetail.css")

Proyecto/Views/Servicio/Index.cshtml
@model IEnumerable<Proyecto.Models.ServicioModel>
@{
    ViewBag.Title = "Servicio";
}

<h2>Servicio</h2>

<table class="table">
    

    @foreach (var item in Model)
    {
        <tr>
            <td class="fila">
                <h4 class="nombre-servicio">@Html.DisplayFor(modelItem => item.Nombre_servicio)</h4>
                <p>
                    @Html.ActionLink("Detalle", "Detalle", new { id = item.Servicio }, new { @class = "btn-detalle" })
                </p>
            </td>
        </tr>
    }
</table>

@Styles.Render("~/Content/stylesservices.css")